[package]
name = "shm-snapshot"
description = "Wrap a shm file so that the read-only partner can snapshot the file partially without explicit synchronization"

version = "0.0.0"
edition = "2021"

[dependencies.shm-fd]
path = "../shm-fd"
version = "0.2.0"

[dependencies.memmap2]
version = "0.9"

[dependencies.memfile]
version = "0.2.1"
optional = true
