[package]
name = "shm-snapshot"
description = "Wrap a shm file so that the read-only partner can snapshot the file partially without explicit synchronization"

version = "0.0.0"
edition = "2021"

[dependencies.memmap2]
version = "0.9"

[dev-dependencies.memfile]
version = "0.3.1"
