[package]
name = "primes"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.shm-fd]
path = "../../shm-fd"
features = ["libc", "memfile", "std"]
[dependencies.bytemuck]
version = "1.7"
[dependencies.memmap2]
version = "0.5"
