[package]
name = "primes"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.shm-state]
path = "../../shm-state"
[dependencies.bytemuck]
version = "1.7"
[dependencies.memmap2]
version = "0.5"
